theme: jekyll-theme-minimal
title: [Xiaoheng Jiang]
description: jiangxiaoheng@zzu.edu.cn
logo: fig/my-photo.jpg
url: http://xg.zzu.edu.cn/bdsd/1599528894250.jhtml[GitHub]
show_downloads: false
google_analytics: 
plugins:
  - jemoji
