theme: jekyll-theme-minimal
title: [Xiaoheng Jiang]
description: jiangxiaoheng@zzu.edu.cn
logo: fig/my-photo.jpg
url: <a href="https://github.com/Li-Chongyi/" target="_blank">[GitHub]</a>  
url: "https://github.com/Li-Chongyi/"  
show_downloads: false
google_analytics: 
plugins:
  - jemoji
